version: "3.8"

services:
  glassfish:
    build: .
    container_name: glassfish-server
   # ports:
    #  - "8090:8080"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - glassfish
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
